site_name: BRO
site_description: Build, Run, Operate
site_url: https://davidbaxterautonomoussystems.github.io/bro-course/
repo_url: https://github.com/DavidBaxterAutonomousSystems/bro-course
repo_name: DavidBaxterAutonomousSystems/bro-course

nav:
  - Home: index.md
  - Overview: overview.md
  - Schedule: schedule.md
  - Build Track: build-track.md
  - Setup: setup.md
  - Resources: resources.md
  - FAQ: faq.md

theme:
  name: mkdocs
